# Generated by Django 5.0.4 on 2024-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historial',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenis_ID', models.IntegerField(null=True)),
                ('Fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('Usuario_ID', models.IntegerField(null=True)),
                ('Accion', models.CharField(max_length=20, verbose_name='Accion')),
            ],
        ),
        migrations.CreateModel(
            name='tenis',
            fields=[
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('Estilo', models.CharField(max_length=50, verbose_name='Estilo')),
                ('Color', models.CharField(max_length=100, verbose_name='Color')),
                ('Cantidad', models.IntegerField()),
                ('Precio_unitario', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='tenis',
            constraint=models.CheckConstraint(check=models.Q(('Cantidad__gte', 0)), name='calzadole_tenis_campo1_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='tenis',
            constraint=models.CheckConstraint(check=models.Q(('Precio_unitario__gte', 0)), name='calzadole_tenis_campo2_positive_check'),
        ),
    ]
