# Generated by Django 5.0.4 on 2024-05-05 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalzadoLE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cantidadtallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talla36', models.IntegerField(default=0)),
                ('Talla37', models.IntegerField(default=0)),
                ('Talla38', models.IntegerField(default=0)),
                ('Talla39', models.IntegerField(default=0)),
                ('Talla40', models.IntegerField(default=0)),
                ('Talla41', models.IntegerField(default=0)),
                ('Talla42', models.IntegerField(default=0)),
                ('Talla43', models.IntegerField(default=0)),
                ('Talla44', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='tenis',
            name='calzadole_tenis_campo1_positive_check',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='Cantidad',
        ),
        migrations.AddField(
            model_name='cantidadtallas',
            name='Tenis_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalzadoLE.tenis'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla36__gte', 0)), name='calzadole_cantidadtallas_campo1_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla37__gte', 0)), name='calzadole_cantidadtallas_campo2_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla38__gte', 0)), name='calzadole_cantidadtallas_campo3_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla39__gte', 0)), name='calzadole_cantidadtallas_campo4_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla40__gte', 0)), name='calzadole_cantidadtallas_campo5_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla41__gte', 0)), name='calzadole_cantidadtallas_campo6_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla42__gte', 0)), name='calzadole_cantidadtallas_campo7_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla43__gte', 0)), name='calzadole_cantidadtallas_campo8_positive_check'),
        ),
        migrations.AddConstraint(
            model_name='cantidadtallas',
            constraint=models.CheckConstraint(check=models.Q(('Talla44__gte', 0)), name='calzadole_cantidadtallas_campo9_positive_check'),
        ),
    ]
