# Generated by Django 5.0.4 on 2024-05-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalzadoLE', '0002_cantidadtallas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla36',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 36'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla37',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 37'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla38',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 38'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla39',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 39'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla40',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 40'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla41',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 41'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla42',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 42'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla43',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 43'),
        ),
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Talla44',
            field=models.IntegerField(default=0, null=True, verbose_name='Talla 44'),
        ),
    ]
