# Generated by Django 5.0.4 on 2024-05-05 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalzadoLE', '0003_alter_cantidadtallas_talla36_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadtallas',
            name='Tenis_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CalzadoLE.tenis'),
        ),
    ]
